apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "mount-deny"
spec:
  kprobes:
  - call: "sys_mount"
    syscall: true
    args:
    - index: 0
      type: "string"
    - index: 1
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/dev/sda1\0"
      matchActions:
      - action: Sigkill
